[package]
name = "radixdb-plugin-macros"
version.workspace = true
edition = "2021"
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
description = "Procedural macros for the safe RadixDB native plugin SDK"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
semver = "1"
sha2 = "0.10"
syn = { version = "2", features = ["full", "extra-traits"] }
uuid = "1"
