[package]
name = "radixdb-catalog"
version.workspace = true
edition = "2021"
rust-version.workspace = true
description = "Generational logical catalog owner for RadixDB"
license-file = "../../LICENSE"
publish = false

[dependencies]
radixdb-core = { path = "../radixdb-core" }

[dev-dependencies]
proptest = "1.4"
