use std::time::Duration;

use radixdb_catalog::{
    MAX_CANONICAL_SQL_BYTES, MAX_CATALOG_EDGES, MAX_CATALOG_FILE_BYTES, MAX_CATALOG_OBJECTS,
    MAX_DEPENDENCY_DEPTH, MAX_DISPLAY_NAME_BYTES, MAX_FIELDS_PER_OBJECT, MAX_HNSW_EF_CONSTRUCTION,
    MAX_HNSW_EF_SEARCH, MAX_HNSW_M, MAX_NORMALIZED_NAME_BYTES, MAX_OBJECT_IDS_PER_FIELD,
    MAX_PAYLOAD_AREA_BYTES, MAX_PAYLOAD_BYTES_PER_OBJECT, MAX_STRING_AREA_BYTES,
    MAX_VECTOR_DIMENSIONS,
};
use radixdb_storage::v6::{
    ArtifactCleanupLimits, CatalogWalReplayLimits, DataOpenLimits, IndexOpenLimits, LeaseLimits,
    ReachabilityLimits, StagingDiscoveryLimits, CATALOG_WAL_RECORD_HEADER_BYTES,
    DEFAULT_EXACT_PAGE_BYTES, DEFAULT_EXACT_PAGE_ENTRIES, DEFAULT_FANOUT_RESIDENT_BYTES,
    DEFAULT_FANOUT_SPILL_BYTES, DEFAULT_HNSW_PAGE_BYTES, DEFAULT_HNSW_PAGE_ENTRIES,
    DEFAULT_MERGE_FAN_IN, DEFAULT_ORDERED_PAGE_BYTES, DEFAULT_ORDERED_PAGE_ENTRIES,
    DEFAULT_SORT_RUN_BYTES, DEFAULT_SORT_RUN_RECORDS, MAX_ACCELERATORS_PER_INDEX_ARTIFACT,
    MAX_ACTIVE_ARTIFACT_BUILDS, MAX_ACTIVE_GENERATION_LEASES, MAX_ARTIFACT_FILE_BYTES,
    MAX_BLOCKS_PER_DATA_ARTIFACT, MAX_BLOOM_BITS_PER_GROUP_COLUMN, MAX_BYTES_PER_VALUE,
    MAX_CATALOG_WAL_RECORD_BYTES, MAX_CATALOG_WAL_REPLAY_BYTES,
    MAX_CATALOG_WAL_REPLAY_TRANSACTIONS, MAX_CLEANUP_ACCOUNTED_BYTES, MAX_CLEANUP_FILES,
    MAX_CLEANUP_MUTATIONS, MAX_CLEANUP_WALL_TIME, MAX_COLUMNS_PER_TABLE, MAX_DATA_DIRECTORY_BYTES,
    MAX_DATA_OPEN_METADATA_BYTES, MAX_DICTIONARY_ITEMS_PER_BLOCK, MAX_ENTRIES_PER_INDEX_PAGE,
    MAX_EXACT_PAGE_DECODE_BYTES, MAX_FANOUT_RESIDENT_BYTES, MAX_FANOUT_SPILL_BYTES,
    MAX_HNSW_GRAPH_DECODE_BYTES, MAX_HNSW_LEVELS, MAX_HNSW_NEIGHBORS_PER_LEVEL,
    MAX_INDEX_DIRECTORY_BYTES, MAX_INDEX_KEY_BYTES, MAX_INDEX_OPEN_METADATA_BYTES, MAX_INDEX_PAGES,
    MAX_INDEX_SECTIONS, MAX_KEY_COLUMNS, MAX_LOGICAL_BYTES_PER_BLOCK,
    MAX_LOGICAL_BYTES_PER_INDEX_PAGE, MAX_MANIFEST_FILE_BYTES, MAX_MERGE_FAN_IN,
    MAX_OPEN_METADATA_BYTES, MAX_ORDERED_PAGE_DECODE_BYTES, MAX_REACHABILITY_BYTES,
    MAX_REACHABLE_IDENTITIES, MAX_ROWS_PER_DATA_ARTIFACT, MAX_ROWS_PER_GROUP,
    MAX_ROW_GROUPS_PER_DATA_ARTIFACT, MAX_SEGMENTS_PER_TABLE_MANIFEST, MAX_SNAPSHOT_MANIFEST_BYTES,
    MAX_SNAPSHOT_MEMBERS, MAX_SNAPSHOT_WAL_BYTES, MAX_SORT_RUN_BYTES,
    MAX_SORT_RUN_DESCRIPTOR_SLOTS, MAX_SORT_RUN_FILES, MAX_SORT_RUN_RECORDS,
    MAX_STAGED_FILES_PER_PUBLICATION, MAX_STAGED_PATH_BYTES, MAX_STAGED_PATH_COMPONENT_BYTES,
    MAX_STAGING_DISCOVERY_BYTES, MAX_STAGING_PUBLICATIONS, MAX_STAGING_RECURSION_DEPTH,
    MAX_STATISTICS_VALUES_BYTES, MAX_STATISTIC_VALUE_BYTES, MAX_STORED_BYTES_PER_BLOCK,
    MAX_STORED_BYTES_PER_INDEX_PAGE, MAX_TABLES_PER_DATABASE, MAX_TOTAL_MANIFESTS_PER_OPEN,
    MAX_TOTAL_SEGMENTS_PER_OPEN,
};

#[test]
fn published_hard_ceilings_do_not_drift_from_the_normative_matrix() {
    assert_eq!(MAX_CATALOG_FILE_BYTES, 512 * 1024 * 1024);
    assert_eq!(MAX_CATALOG_OBJECTS, 262_144);
    assert_eq!(MAX_CATALOG_EDGES, 1_048_576);
    assert_eq!(MAX_PAYLOAD_AREA_BYTES, 256 * 1024 * 1024);
    assert_eq!(MAX_STRING_AREA_BYTES, 128 * 1024 * 1024);
    assert_eq!(MAX_FIELDS_PER_OBJECT, 64);
    assert_eq!(MAX_PAYLOAD_BYTES_PER_OBJECT, 16 * 1024 * 1024);
    assert_eq!(MAX_NORMALIZED_NAME_BYTES, 1_024);
    assert_eq!(MAX_DISPLAY_NAME_BYTES, 4_096);
    assert_eq!(MAX_CANONICAL_SQL_BYTES, 16 * 1024 * 1024);
    assert_eq!(MAX_OBJECT_IDS_PER_FIELD, 4_096);
    assert_eq!(MAX_DEPENDENCY_DEPTH, 256);
    assert_eq!(MAX_VECTOR_DIMENSIONS, 65_535);
    assert_eq!(MAX_HNSW_M, 128);
    assert_eq!(MAX_HNSW_EF_CONSTRUCTION, 4_096);
    assert_eq!(MAX_HNSW_EF_SEARCH, 4_096);

    assert_eq!(MAX_CATALOG_WAL_REPLAY_BYTES, 1024 * 1024 * 1024);
    assert_eq!(MAX_CATALOG_WAL_REPLAY_TRANSACTIONS, 262_144);
    assert_eq!(
        MAX_CATALOG_WAL_RECORD_BYTES,
        512 * 1024 * 1024 + CATALOG_WAL_RECORD_HEADER_BYTES as u64
    );

    assert_eq!(MAX_MANIFEST_FILE_BYTES, 256 * 1024 * 1024);
    assert_eq!(MAX_TABLES_PER_DATABASE, 262_144);
    assert_eq!(MAX_SEGMENTS_PER_TABLE_MANIFEST, 1_048_576);
    assert_eq!(MAX_TOTAL_MANIFESTS_PER_OPEN, 262_145);
    assert_eq!(MAX_TOTAL_SEGMENTS_PER_OPEN, 4_194_304);
    assert_eq!(MAX_OPEN_METADATA_BYTES, 512 * 1024 * 1024);
    assert_eq!(MAX_REACHABLE_IDENTITIES, 8_388_608);
    assert_eq!(MAX_REACHABILITY_BYTES, 1024 * 1024 * 1024);

    assert_eq!(MAX_ARTIFACT_FILE_BYTES, 64 * 1024 * 1024 * 1024);
    assert_eq!(MAX_ROWS_PER_DATA_ARTIFACT, u32::MAX as u64);
    assert_eq!(MAX_COLUMNS_PER_TABLE, 4_096);
    assert_eq!(MAX_ROW_GROUPS_PER_DATA_ARTIFACT, 65_536);
    assert_eq!(MAX_ROWS_PER_GROUP, 65_536);
    assert_eq!(MAX_BLOCKS_PER_DATA_ARTIFACT, 4_194_304);
    assert_eq!(MAX_DATA_DIRECTORY_BYTES, 256 * 1024 * 1024);
    assert_eq!(MAX_STORED_BYTES_PER_BLOCK, 256 * 1024 * 1024);
    assert_eq!(MAX_LOGICAL_BYTES_PER_BLOCK, 512 * 1024 * 1024);
    assert_eq!(MAX_STATISTICS_VALUES_BYTES, 64 * 1024 * 1024);
    assert_eq!(MAX_STATISTIC_VALUE_BYTES, 1024 * 1024);
    assert_eq!(MAX_BLOOM_BITS_PER_GROUP_COLUMN, 67_108_864);
    assert_eq!(MAX_BYTES_PER_VALUE, 256 * 1024 * 1024);
    assert_eq!(MAX_DICTIONARY_ITEMS_PER_BLOCK, 16_777_216);

    assert_eq!(MAX_ACCELERATORS_PER_INDEX_ARTIFACT, 4_096);
    assert_eq!(MAX_INDEX_SECTIONS, 16_384);
    assert_eq!(MAX_INDEX_PAGES, 4_194_304);
    assert_eq!(MAX_INDEX_DIRECTORY_BYTES, 320 * 1024 * 1024);
    assert_eq!(MAX_KEY_COLUMNS, 64);
    assert_eq!(MAX_INDEX_KEY_BYTES, 1024 * 1024);
    assert_eq!(MAX_ENTRIES_PER_INDEX_PAGE, 1_048_576);
    assert_eq!(MAX_STORED_BYTES_PER_INDEX_PAGE, 64 * 1024 * 1024);
    assert_eq!(MAX_LOGICAL_BYTES_PER_INDEX_PAGE, 256 * 1024 * 1024);
    assert_eq!(MAX_EXACT_PAGE_DECODE_BYTES, 512 * 1024 * 1024);
    assert_eq!(MAX_ORDERED_PAGE_DECODE_BYTES, 512 * 1024 * 1024);
    assert_eq!(MAX_HNSW_GRAPH_DECODE_BYTES, 1024 * 1024 * 1024);
    assert_eq!(MAX_HNSW_LEVELS, 64);
    assert_eq!(MAX_HNSW_NEIGHBORS_PER_LEVEL, 8_192);
    assert_eq!(DEFAULT_EXACT_PAGE_ENTRIES, 4_096);
    assert_eq!(DEFAULT_EXACT_PAGE_BYTES, 4 * 1024 * 1024);
    assert_eq!(DEFAULT_ORDERED_PAGE_ENTRIES, 4_096);
    assert_eq!(DEFAULT_ORDERED_PAGE_BYTES, 4 * 1024 * 1024);
    assert_eq!(DEFAULT_HNSW_PAGE_ENTRIES, 4_096);
    assert_eq!(DEFAULT_HNSW_PAGE_BYTES, 4 * 1024 * 1024);

    assert_eq!(DEFAULT_SORT_RUN_RECORDS, 65_536);
    assert_eq!(DEFAULT_SORT_RUN_BYTES, 64 * 1024 * 1024);
    assert_eq!(MAX_SORT_RUN_RECORDS, 1_048_576);
    assert_eq!(MAX_SORT_RUN_BYTES, 256 * 1024 * 1024);
    assert_eq!(MAX_SORT_RUN_FILES, 4_096);
    assert_eq!(DEFAULT_MERGE_FAN_IN, 16);
    assert_eq!(MAX_MERGE_FAN_IN, 32);
    assert_eq!(MAX_SORT_RUN_DESCRIPTOR_SLOTS, 33);
    assert_eq!(DEFAULT_FANOUT_RESIDENT_BYTES, 256 * 1024 * 1024);
    assert_eq!(DEFAULT_FANOUT_SPILL_BYTES, 64 * 1024 * 1024 * 1024);
    assert_eq!(MAX_FANOUT_RESIDENT_BYTES, 1024 * 1024 * 1024);
    assert_eq!(MAX_FANOUT_SPILL_BYTES, 256 * 1024 * 1024 * 1024);

    assert_eq!(MAX_SNAPSHOT_MEMBERS, 8_388_608);
    assert_eq!(MAX_SNAPSHOT_MANIFEST_BYTES, 805_306_672);
    assert_eq!(MAX_SNAPSHOT_WAL_BYTES, MAX_ARTIFACT_FILE_BYTES);
    assert_eq!(MAX_STAGING_PUBLICATIONS, 65_536);
    assert_eq!(MAX_STAGED_FILES_PER_PUBLICATION, 8_388_608);
    assert_eq!(MAX_STAGED_PATH_BYTES, 4_096);
    assert_eq!(MAX_STAGED_PATH_COMPONENT_BYTES, 255);
    assert_eq!(MAX_STAGING_RECURSION_DEPTH, 256);
    assert_eq!(MAX_STAGING_DISCOVERY_BYTES, 1024 * 1024 * 1024);
    assert_eq!(MAX_CLEANUP_FILES, 1_000_000);
    assert_eq!(MAX_CLEANUP_MUTATIONS, 1_000_000);
    assert_eq!(MAX_CLEANUP_ACCOUNTED_BYTES, 1024 * 1024 * 1024 * 1024);
    assert_eq!(MAX_CLEANUP_WALL_TIME, Duration::from_secs(60 * 60));
    assert_eq!(MAX_ACTIVE_GENERATION_LEASES, 4_096);
    assert_eq!(MAX_ACTIVE_ARTIFACT_BUILDS, 1_024);
}

#[test]
fn runtime_limit_owners_accept_only_positive_values_at_or_below_hard_ceilings() {
    assert!(DataOpenLimits::new(MAX_DATA_OPEN_METADATA_BYTES).is_ok());
    assert!(DataOpenLimits::new(0).is_err());
    assert!(DataOpenLimits::new(MAX_DATA_OPEN_METADATA_BYTES + 1).is_err());

    assert!(IndexOpenLimits::new(MAX_INDEX_OPEN_METADATA_BYTES).is_ok());
    assert!(IndexOpenLimits::new(0).is_err());
    assert!(IndexOpenLimits::new(MAX_INDEX_OPEN_METADATA_BYTES + 1).is_err());

    assert!(ReachabilityLimits::new(MAX_REACHABLE_IDENTITIES, MAX_REACHABILITY_BYTES).is_ok());
    assert!(ReachabilityLimits::new(0, MAX_REACHABILITY_BYTES).is_err());
    assert!(ReachabilityLimits::new(MAX_REACHABLE_IDENTITIES + 1, MAX_REACHABILITY_BYTES).is_err());
    let reachability = ReachabilityLimits::default();
    assert!(reachability
        .with_generation_counts(MAX_TOTAL_MANIFESTS_PER_OPEN, MAX_TOTAL_SEGMENTS_PER_OPEN)
        .is_ok());
    assert!(reachability
        .with_generation_counts(0, MAX_TOTAL_SEGMENTS_PER_OPEN)
        .is_err());
    assert!(reachability
        .with_generation_counts(
            MAX_TOTAL_MANIFESTS_PER_OPEN + 1,
            MAX_TOTAL_SEGMENTS_PER_OPEN
        )
        .is_err());

    assert!(CatalogWalReplayLimits::new(
        MAX_CATALOG_WAL_REPLAY_BYTES,
        MAX_CATALOG_WAL_REPLAY_TRANSACTIONS,
        MAX_CATALOG_WAL_RECORD_BYTES,
    )
    .is_ok());
    assert!(CatalogWalReplayLimits::new(
        CATALOG_WAL_RECORD_HEADER_BYTES as u64 - 1,
        1,
        MAX_CATALOG_WAL_RECORD_BYTES,
    )
    .is_err());
    assert!(CatalogWalReplayLimits::new(
        MAX_CATALOG_WAL_REPLAY_BYTES + 1,
        MAX_CATALOG_WAL_REPLAY_TRANSACTIONS,
        MAX_CATALOG_WAL_RECORD_BYTES,
    )
    .is_err());

    assert!(LeaseLimits::new(MAX_ACTIVE_GENERATION_LEASES, MAX_ACTIVE_ARTIFACT_BUILDS).is_ok());
    assert!(LeaseLimits::new(0, MAX_ACTIVE_ARTIFACT_BUILDS).is_err());
    assert!(
        LeaseLimits::new(MAX_ACTIVE_GENERATION_LEASES + 1, MAX_ACTIVE_ARTIFACT_BUILDS).is_err()
    );

    assert!(StagingDiscoveryLimits::new(
        MAX_STAGING_PUBLICATIONS,
        MAX_STAGED_FILES_PER_PUBLICATION,
        MAX_STAGED_PATH_BYTES,
        MAX_STAGING_RECURSION_DEPTH,
        MAX_STAGING_DISCOVERY_BYTES,
    )
    .is_ok());
    assert!(StagingDiscoveryLimits::new(
        0,
        MAX_STAGED_FILES_PER_PUBLICATION,
        MAX_STAGED_PATH_BYTES,
        MAX_STAGING_RECURSION_DEPTH,
        MAX_STAGING_DISCOVERY_BYTES,
    )
    .is_err());
    assert!(StagingDiscoveryLimits::new(
        MAX_STAGING_PUBLICATIONS + 1,
        MAX_STAGED_FILES_PER_PUBLICATION,
        MAX_STAGED_PATH_BYTES,
        MAX_STAGING_RECURSION_DEPTH,
        MAX_STAGING_DISCOVERY_BYTES,
    )
    .is_err());

    assert!(ArtifactCleanupLimits::new(
        MAX_CLEANUP_FILES,
        MAX_CLEANUP_ACCOUNTED_BYTES,
        MAX_CLEANUP_MUTATIONS,
        MAX_CLEANUP_MUTATIONS,
        MAX_CLEANUP_ACCOUNTED_BYTES,
        Duration::ZERO,
        MAX_CLEANUP_WALL_TIME,
    )
    .is_ok());
    assert!(ArtifactCleanupLimits::new(
        0,
        MAX_CLEANUP_ACCOUNTED_BYTES,
        MAX_CLEANUP_MUTATIONS,
        MAX_CLEANUP_MUTATIONS,
        MAX_CLEANUP_ACCOUNTED_BYTES,
        Duration::ZERO,
        MAX_CLEANUP_WALL_TIME,
    )
    .is_err());
    assert!(ArtifactCleanupLimits::new(
        MAX_CLEANUP_FILES + 1,
        MAX_CLEANUP_ACCOUNTED_BYTES,
        MAX_CLEANUP_MUTATIONS,
        MAX_CLEANUP_MUTATIONS,
        MAX_CLEANUP_ACCOUNTED_BYTES,
        Duration::ZERO,
        MAX_CLEANUP_WALL_TIME,
    )
    .is_err());
}
