[package]
name = "radixdb-plugin-abi"
version.workspace = true
edition = "2021"
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
description = "Stable low-level C ABI for trusted RadixDB native plugins"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
